# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# encoding: utf-8
AdminUser.create(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
AdminUser.create(email: 'emmajouffroypro@gmail.com', password: 'emmajou', password_confirmation: 'emmajou')
AdminUser.create(email: 'noemilamane2@gmail.com', password: 'noemil', password_confirmation: 'noemil')
AdminUser.create(email: 'eliemargoet@gmail.com', password: 'eliema', password_confirmation: 'eliema')
AdminUser.create(email: 'fleurgriffon@gmail.com', password: 'fleurg', password_confirmation: 'fleurg')
AdminUser.create(email: 'florianlaville33@gmail.com', password: 'florian', password_confirmation: 'florian')
AdminUser.create(email: 'margauxdelafontaine@gmail.com', password: 'margaux', password_confirmation: 'margaux')
AdminUser.create(email: 'swann.latasa@gmail.com', password: 'swannl', password_confirmation: 'swannl')
AdminUser.create(email: 'lafon_aurelien@orange.fr', password: 'aurelien', password_confirmation: 'aurelien')



not1 = Notion.create(name:"vie", :photo => File.new(__dir__+"/files/notions/vie.jpg"))
not2 = Notion.create(name:"âge", :photo => File.new(__dir__+"/files/notions/age.jpg"))
not3 = Notion.create(name:"mort", :photo => File.new(__dir__+"/files/notions/mort.jpg"))
not4 = Notion.create(name:"alimentation", :photo => File.new(__dir__+"/files/notions/alimentation.jpg"))
not5 = Notion.create(name:"aliment", :photo => File.new(__dir__+"/files/notions/aliment.jpg"))
not6 = Notion.create(name:"jeu", :photo => File.new(__dir__+"/files/notions/jeu.jpg"))
not7 = Notion.create(name:"sport", :photo => File.new(__dir__+"/files/notions/sport.jpg"))
not8 = Notion.create(name:"commerce", :photo => File.new(__dir__+"/files/notions/commerce.jpg"))
not9 = Notion.create(name:"argent", :photo => File.new(__dir__+"/files/notions/argent.jpg"))
not10 = Notion.create(name:"économie", :photo => File.new(__dir__+"/files/notions/economie.jpg"))
not11 = Notion.create(name:"entreprise", :photo => File.new(__dir__+"/files/notions/entreprise.jpg"))
not12 = Notion.create(name:"possession", :photo => File.new(__dir__+"/files/notions/possession.jpg"))
not13 = Notion.create(name:"communication", :photo => File.new(__dir__+"/files/notions/communication.jpg"))
not14 = Notion.create(name:"langage", :photo =>  File.new(__dir__+"/files/notions/langage.jpg"))
not15 = Notion.create(name:"écriture", :photo => File.new(__dir__+"/files/notions/ecriture.jpg"))
not16 = Notion.create(name:"informer", :photo => File.new(__dir__+"/files/notions/informer.jpg"))
not17 = Notion.create(name:"télécommunication", :photo => File.new(__dir__+"/files/notions/telecommunication.jpg"))
not18 = Notion.create(name:"internet", :photo => File.new(__dir__+"/files/notions/internet.jpg"))
not19 = Notion.create(name:"nom", :photo => File.new(__dir__+"/files/notions/nom.jpg"))
not20 = Notion.create(name:"mouvement", :photo => File.new(__dir__+"/files/notions/mouvement.jpg"))
not21 = Notion.create(name:"déplacement", :photo => File.new(__dir__+"/files/notions/deplacement.jpg"))
not22 = Notion.create(name:"transport", :photo => File.new(__dir__+"/files/notions/transport.jpg"))
not23 = Notion.create(name:"bateau", :photo => File.new(__dir__+"/files/notions/bateau.jpg"))
not24 = Notion.create(name:"automobile", :photo => File.new(__dir__+"/files/notions/automobile.jpg"))
not25 = Notion.create(name:"train", :photo => File.new(__dir__+"/files/notions/train.jpg"))
not26 = Notion.create(name:"avion", :photo => File.new(__dir__+"/files/notions/avion.jpg"))
not27 = Notion.create(name:"deux-roues", :photo => File.new(__dir__+"/files/notions/deuxroues.jpg"))
not28 = Notion.create(name:"corps", :photo => File.new(__dir__+"/files/notions/corps.jpg"))
not29 = Notion.create(name:"organe", :photo => File.new(__dir__+"/files/notions/organe.jpg"))
not30 = Notion.create(name:"santé", :photo => File.new(__dir__+"/files/notions/sante.jpg"))
not31 = Notion.create(name:"hygiène", :photo => File.new(__dir__+"/files/notions/hygiene.jpg"))
not32 = Notion.create(name:"sommeil", :photo => File.new(__dir__+"/files/notions/sommeil.jpg"))
not33 = Notion.create(name:"position", :photo => File.new(__dir__+"/files/notions/position.jpg"))
not34 = Notion.create(name:"sexualité", :photo => File.new(__dir__+"/files/notions/sexualite.jpg"))
not35 = Notion.create(name:"technique", :photo => File.new(__dir__+"/files/notions/technique.jpg"))
not36 = Notion.create(name:"instrument", :photo => File.new(__dir__+"/files/notions/instrument.jpg"))
not37 = Notion.create(name:"ordinateurs", :photo => File.new(__dir__+"/files/notions/ordinateur.jpg"))
not38 = Notion.create(name:"al", :photo => File.new(__dir__+"/files/notions/animaux.jpg"))
not39 = Notion.create(name:"Invertébré", :photo => File.new(__dir__+"/files/notions/invertebres.jpg"))
not40 = Notion.create(name:"Vertébré", :photo => File.new(__dir__+"/files/notions/vertebre.jpg"))
not41 = Notion.create(name:"Plante", :photo => File.new(__dir__+"/files/notions/plante.jpg"))
not42 = Notion.create(name:"Pouvoir", :photo => File.new(__dir__+"/files/notions/pouvoir.jpg"))
not43 = Notion.create(name:"Politique", :photo => File.new(__dir__+"/files/notions/politique.jpg"))
not44 = Notion.create(name:"Pays", :photo => File.new(__dir__+"/files/notions/pays.jpg"))
not45 = Notion.create(name:"Justice", :photo => File.new(__dir__+"/files/notions/justice.jpg"))
not46 = Notion.create(name:"Sécurité", :photo => File.new(__dir__+"/files/notions/securite.jpg"))
not47 = Notion.create(name:"Militaire", :photo => File.new(__dir__+"/files/notions/militaire.jpg"))
not48 = Notion.create(name:"Famille", :photo => File.new(__dir__+"/files/notions/famille.jpg"))
not49 = Notion.create(name:"Mariage", :photo => File.new(__dir__+"/files/notions/mariage.jpg"))
not50 = Notion.create(name:"Matière", :photo => File.new(__dir__+"/files/notions/matiere.jpg"))
not51 = Notion.create(name:"Atome", :photo => File.new(__dir__+"/files/notions/atome.jpg"))
not52 = Notion.create(name:"Déchet", :photo => File.new(__dir__+"/files/notions/dechet.jpg"))
not53 = Notion.create(name:"Feu", :photo => File.new(__dir__+"/files/notions/feu.jpg"))
not54 = Notion.create(name:"Eau", :photo => File.new(__dir__+"/files/notions/eau.jpg"))
not55 = Notion.create(name:"Force", :photo => File.new(__dir__+"/files/notions/force.jpg"))
not56 = Notion.create(name:"Edifice", :photo => File.new(__dir__+"/files/notions/edifice.jpg"))
not57 = Notion.create(name:"Ville", :photo => File.new(__dir__+"/files/notions/ville.jpg"))
not58 = Notion.create(name:"Voie", :photo => File.new(__dir__+"/files/notions/voie.jpg"))
not59 = Notion.create(name:"Espace", :photo => File.new(__dir__+"/files/notions/espace.jpg"))
not60 = Notion.create(name:"Orientation", :photo => File.new(__dir__+"/files/notions/orientation.jpg"))
not61 = Notion.create(name:"Distance", :photo => File.new(__dir__+"/files/notions/distance.jpg"))
not62 = Notion.create(name:"Univers", :photo => File.new(__dir__+"/files/notions/univers.jpg"))
not63 = Notion.create(name:"Terre", :photo => File.new(__dir__+"/files/notions/terre.jpg"))
not64 = Notion.create(name:"Mer", :photo => File.new(__dir__+"/files/notions/mer.jpg"))
not65 = Notion.create(name:"Continent", :photo => File.new(__dir__+"/files/notions/continent.jpg"))
not66 = Notion.create(name:"Climat", :photo => File.new(__dir__+"/files/notions/climat.jpg"))
not67 = Notion.create(name:"Saison", :photo => File.new(__dir__+"/files/notions/saison.jpg"))
not68 = Notion.create(name:"Temps", :photo => File.new(__dir__+"/files/notions/temps.jpg"))
not69 = Notion.create(name:"Date-Calendrier", :photo => File.new(__dir__+"/files/notions/calendrier.jpg"))
not70 = Notion.create(name:"Fait", :photo => File.new(__dir__+"/files/notions/fait.jpg"))
not71 = Notion.create(name:"Intellect", :photo => File.new(__dir__+"/files/notions/intellect.jpg"))
not72 = Notion.create(name:"Savoir", :photo => File.new(__dir__+"/files/notions/savoir.jpg"))
not73 = Notion.create(name:"Apprentissage", :photo => File.new(__dir__+"/files/notions/apprentissage.jpg"))
not74 = Notion.create(name:"Sens", :photo => File.new(__dir__+"/files/notions/sens.jpg"))
not75 = Notion.create(name:"Oui-Non", :photo => File.new(__dir__+"/files/notions/ouinon.jpg"))
not76 = Notion.create(name:"Verité", :photo => File.new(__dir__+"/files/notions/verite.jpg"))
not77 = Notion.create(name:"Société", :photo => File.new(__dir__+"/files/notions/societe.jpg"))
not78 = Notion.create(name:"Fête", :photo => File.new(__dir__+"/files/notions/fete.jpg"))
not79 = Notion.create(name:"Esprit", :photo => File.new(__dir__+"/files/notions/esprit.jpg"))
not80 = Notion.create(name:"Religion", :photo => File.new(__dir__+"/files/notions/religion.jpg"))
not81 = Notion.create(name:"Nombre", :photo => File.new(__dir__+"/files/notions/nom.jpg"))
not82 = Notion.create(name:"Mesure", :photo => File.new(__dir__+"/files/notions/mesure.jpg"))
not83 = Notion.create(name:"Dimension", :photo => File.new(__dir__+"/files/notions/dimension.jpg"))
not84 = Notion.create(name:"Sentiment", :photo => File.new(__dir__+"/files/notions/sentiment.jpg"))
not85 = Notion.create(name:"Salutation", :photo => File.new(__dir__+"/files/notions/salutation.jpg"))
not86 = Notion.create(name:"Faire", :photo => File.new(__dir__+"/files/notions/faire.jpg"))
not87 = Notion.create(name:"Finalité", :photo => File.new(__dir__+"/files/notions/finalite.jpg"))
not88 = Notion.create(name:"Travail", :photo => File.new(__dir__+"/files/notions/travail.jpg"))
not89 = Notion.create(name:"Agriculture", :photo => File.new(__dir__+"/files/notions/agriculture.jpg"))
not90 = Notion.create(name:"Industrie", :photo => File.new(__dir__+"/files/notions/industrie.jpg"))
not91 = Notion.create(name:"Vision", :photo => File.new(__dir__+"/files/notions/vision.jpg"))
not92 = Notion.create(name:"Audition", :photo => File.new(__dir__+"/files/notions/audition.jpg"))
not93 = Notion.create(name:"Toucher", :photo => File.new(__dir__+"/files/notions/toucher.jpg"))
not94 = Notion.create(name:"Être humain", :photo => File.new(__dir__+"/files/notions/etrehumain.jpg"))
not95 = Notion.create(name:"Soi", :photo => File.new(__dir__+"/files/notions/soi.jpg"))
not96 = Notion.create(name:"Objet", :photo => File.new(__dir__+"/files/notions/objets.jpg"))
not97 = Notion.create(name:"Textile", :photo => File.new(__dir__+"/files/notions/textile.jpg"))
not98 = Notion.create(name:"Art", :photo => File.new(__dir__+"/files/notions/art.jpg"))
